#!/bin/sh
#
#   Copyright 2012 Jonathan M. Reid. See LICENSE.txt
#   Created by: Jon Reid, http://qualitycoding.org/
#   Source: https://github.com/jonreid/XcodeCoverage
#

source envcov.sh

remove_old_report()
{
    pushd ${PROJECT_DIR}
    if [ -e ${COVERAGE_OUTPUT_DIR} ]; then
        rm -r ${COVERAGE_OUTPUT_DIR}
    fi
    popd
}

enter_lcov_dir()
{
    cd ${PROJECT_DIR}
    mkdir -p ${COVERAGE_OUTPUT_DIR}
    cd ${COVERAGE_OUTPUT_DIR}
}

gather_coverage()
{
    "${LCOV}" --capture -b "${SRCROOT}" -d "${OBJ_DIR}" -o ${LCOV_INFO}
}

exclude_data()
{
    "${LCOV}" --remove ${LCOV_INFO} "/Applications/Xcode.app/*" -d "${OBJ_DIR}" -o ${LCOV_INFO}
    "${LCOV}" --remove ${LCOV_INFO} "main.m" -d "${OBJ_DIR}" -o ${LCOV_INFO}
    "${LCOV}" --remove ${LCOV_INFO} "UnitTests/**" -d "${OBJ_DIR}" -o ${LCOV_INFO}
    "${LCOV}" --remove ${LCOV_INFO} "IntegrationTests/**" -d "${OBJ_DIR}" -o ${LCOV_INFO}
}

generate_report()
{
    "${LCOV_PATH}/genhtml" --output-directory ${COVERAGE_OUTPUT_PATH} ${LCOV_INFO} --legend
}

remove_old_report
enter_lcov_dir
gather_coverage
exclude_data
generate_report
