#!/bin/sh
#
#   Copyright 2012 Jonathan M. Reid. See LICENSE.txt
#   Created by: Jon Reid, http://qualitycoding.org/
#   Source: https://github.com/jonreid/XcodeCoverage
#

source envcov.sh

remove_old_report()
{
    # TODO this blows away the ENTIRE build directory
    # will need to make this more selective as build develops
    pushd ${PROJECT_DIR}
    if [ -e build ]; then
        rm -r build
    fi
    popd
}

enter_lcov_dir()
{
    cd ${PROJECT_DIR}
    mkdir -p build/test-coverage
    cd build/test-coverage
}

gather_coverage()
{
    "${LCOV}" --capture -b "${SRCROOT}" -d "${OBJ_DIR}" -o ${LCOV_INFO}
}

exclude_data()
{
    "${LCOV}" --remove ${LCOV_INFO} "/Applications/Xcode.app/*" -d "${OBJ_DIR}" -o ${LCOV_INFO}
    "${LCOV}" --remove ${LCOV_INFO} "main.m" -d "${OBJ_DIR}" -o ${LCOV_INFO}
    # Remove other patterns here...
}

generate_report()
{
    "${LCOV_PATH}/genhtml" --output-directory ${COVERAGE_OUTPUT_PATH} ${LCOV_INFO}
}

# create this env var here; TODO improve this whole sheel script setup
COVERAGE_OUTPUT_PATH=${PROJECT_DIR}/build/test-coverage

remove_old_report
enter_lcov_dir
gather_coverage
exclude_data
generate_report
